import assert from "assert"; import { runVorixen } from "../src/pipeline/vorixen-pipeline.js"; import { validateConfig } from "../src/core/config.js";
function test(name,fn){try{fn(); console.log(`PASS ${name}`);}catch(err){console.error(`FAIL ${name}`); console.error(err); process.exitCode=1;}}
test("config válida",()=>{assert.equal(validateConfig(),true);});
test("base gravable ICA posterior a 2017 activa normativa",()=>{const r=runVorixen("me puedes decir cual es la base gravable del ica a partir de 2017?"); assert.equal(r.mode,"normative_query"); assert.equal(r.runtime.status,"ready_for_legal_execution"); assert.ok(r.output.includes("Ley 1819 de 2016"));});
test("hecho generador del ICA activa tema jurídico",()=>{const r=runVorixen("háblame sobre el hecho generador del ICA"); assert.equal(r.mode,"normative_query"); assert.equal(r.runtime.status,"ready_for_legal_execution"); assert.ok(r.output.includes("Hecho generador del ICA")); assert.ok(r.output.includes("Ley 14 de 1983"));});
test("typos leves en hecho generador ICA siguen activando jurídico",()=>{const r=runVorixen("habloame so9bre ewl hecho generador del ica"); assert.equal(r.mode,"normative_query"); assert.notEqual(r.runtime.status,"non_legal_passthrough");});
test("petición de dictamen usa último tema jurídico",()=>{const sessionId="test-dictamen"; runVorixen("me puedes decir cual es la base gravable del ica a partir de 2017?",{sessionId}); const r=runVorixen("tu respuesta es muy superficial, damela tipo dictamen de revisor fiscal",{sessionId}); assert.equal(r.mode,"format_transform"); assert.equal(r.outputMode,"fiscal_auditor_opinion"); assert.ok(r.output.includes("DICTAMEN TÉCNICO DE REVISOR FISCAL")); assert.ok(r.output.includes("Base gravable del ICA"));});
test("caso concreto incompleto activa procedimiento",()=>{const r=runVorixen("mi empresa tiene un caso de hecho generador de ICA"); assert.equal(r.mode,"concrete_case"); assert.equal(r.runtime.status,"procedural_action_required");});
test("no jurídico sigue como no jurídico",()=>{const r=runVorixen("hola como estas"); assert.equal(r.mode,"non_legal"); assert.equal(r.runtime.status,"non_legal_passthrough");});
test("sin lenguaje blando",()=>{const r=runVorixen("háblame sobre el hecho generador del ICA"); const out=r.output.toLowerCase(); assert.ok(!out.includes("podría")); assert.ok(!out.includes("sería recomendable")); assert.ok(!out.includes("opción"));});
test("estructura obligatoria presente",()=>{const r=runVorixen("háblame sobre el hecho generador del ICA"); assert.ok(r.output.includes("NORMA")); assert.ok(r.output.includes("HECHO ACTIVADOR")); assert.ok(r.output.includes("ACCIÓN")); assert.ok(r.output.includes("FINALIDAD JURÍDICA"));});
test("concepto jurídico por hablame",()=>{const r=runVorixen("hablame sobre el hecho generador de ica"); assert.equal(r.outputMode,"legal_concept"); assert.ok(r.output.includes("CONCEPTO JURÍDICO"));});
test("sujeto pasivo ICA activa tema jurídico",()=>{const r=runVorixen("qué es el sujeto pasivo del ICA"); assert.equal(r.mode,"normative_query"); assert.ok(r.output.includes("Sujeto pasivo del ICA"));});
test("procedimiento tributario activa tema jurídico",()=>{const r=runVorixen("háblame del procedimiento tributario territorial"); assert.equal(r.mode,"normative_query"); assert.notEqual(r.runtime.status,"non_legal_passthrough");});
process.exit(process.exitCode||0);
